### PR TITLE
Change to use glossarist gem

### LINKED ISSUE #30: Migrate to latest Glossarist YAML format
From: https://github.com/geolexica/jekyll-geolexica/issues/14

### PR DESCRIPTION
**Pull request by ronaldtse**
Fixes #30

This is a WIP. @HassanAkbar can you please help complete this?

The way to reproduce is as follows:

```
bundle exec tc211-termbase-xlsx2yaml "20231214 Multi-Lingual Glossary – Published __unlocked__ with Math.xlsx"
```

[20231214 Multi-Lingual Glossary – Published __unlocked__ with Math.xlsx](https://github.com/geolexica/tc211-termbase/files/14233505/20231214.Multi-Lingual.Glossary.Published.__unlocked__.with.Math.xlsx)

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse Tried to run this locally and run into `relaton-un` exception which is already reported here -> https://github.com/relaton/relaton-un/issues/14

Will try to work on the code based on the test file, but I think to test this completely we will have to wait for the fix.

**Comment by ronaldtse** [comment]
@HassanAkbar please manually remove this cell and fix other issues. There is no reason to be blocked by it.

**Comment by ronaldtse** [comment]
@HassanAkbar the issue is resolved. Can you continue? Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse this is now ready for review.

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar !

**Pull request merged**
